### ISSUE TITLE
French words converting into Special Characters while data upload using Google sheet API

### ISSUE THREAD

**Issue by knvsg01** [SAP/abap-alv-google-upload-sheet#13] opened 2022-04-07 18:37 UTC
Hello Team,

We need your help in resolving the following issue.
We are running a report in SAP and uploading the output in Google sheet folder using Google sheet API as mentioned in Github project.
Some of the French words are converted into different special characters. 

Please find the attached screenshot.
If the data  is in English it is showing correctly.
If the data is in French ("Sécurité"), those are converted into special characters as "S��curit��".

**Comment by SAPSM** [comment] 2022-06-03 13:21
Hi knvsg01,

You addressed the issue already via the SAP support, although this is a sample project without official maintenance pledge.
Anyway, as also stated there. This looks like a typical encoding problem upon creating the data, that is then uploaded to Google Drive. The problem is to be found in the exporting step when encoding the data. When using the standard export measures, this problem won't arise.

Kind Regards,
Sebastian

**Comment by SAPSM** [comment] 2022-06-03 13:23
Closed as already handled on goodwill base in the official SAP maintenance channel. In a nutshell: Encoding problem in the exporting step beforehand the actual upload to Google Drive.

**Closed as completed** 2022-06-03 13:23 UTC
Labels: invalid, wontfix
