### ISSUE TITLE
Exporting ALV Grid data leading to blank values in googlesheet for some fields

### ISSUE THREAD

**Issue by joginadh** [SAP/abap-alv-google-upload-sheet#20] opened 2022-09-01 11:08 UTC
Hi Team,

I have recently integrated our SAP system(s) with GoogleDrive and am able to export the ALV Grid Data successfully to Googlesheets.
Could see some transactions are having issues in exporting their ALV grid data and leading to blank values for some fields or columns.
Ex: SNOTE TCode ==> Exporting the Notes status to googlesheets is leading to blank value for field "Short Description".

![image](https://user-images.githubusercontent.com/112626188/187899778-4730cd1f-70cd-4926-a9bd-871a0ecc3728.png)

![image](https://user-images.githubusercontent.com/112626188/187899880-9dc7c97c-db79-4862-ab16-347dc4c027bb.png)

Thanks
Jogi

**Comment by SAPSM** [comment] 2022-09-26 12:24
Hi Jogi,

Does this issue occur exclusively in the case where exporting to **Google Sheets**? If it also occurs when exporting to plain Office Open XML (Microsoft Excel) format, the root cause must be further traced in that direction. If you can answer that with yes, i.e. if it is a general export issue, please report an incident on SAP component **BC-SRV-ALV**. Otherwise, please report back here.

Kind Regards,
Sebastian

**Comment by joginadh** [comment] 2022-09-26 16:16
Hi SAPSM,

Thanks for your reply.
There is no issue upon exporting using EXCEL XXL Format, but we have issue while using EXCEL MHTML format and Excel Office Open XML format XLSX.
![image](https://user-images.githubusercontent.com/112626188/192326513-ca164f16-8fc8-487c-8575-87497fea6de5.png)

Issue is there while exporting using EXCEL MHTML format and Excel Office Open XML XLSX Format
![image](https://user-images.githubusercontent.com/112626188/192327174-01ae10bb-805b-457f-9332-4a331e2a37b2.png)
![image](https://user-images.githubusercontent.com/112626188/192327408-9aef78da-1c54-435f-a26e-218465100ccc.png)
![image](https://user-images.githubusercontent.com/112626188/192327953-e0f711d7-1a39-47bb-9efc-67d8fa0d1054.png)


Thanks
Joginadham

**Comment by SAPSM** [comment] 2022-09-27 08:06
Hi Jogi,

As I already assumed, this has no relation to the provided Google Sheets Integration, but it is about a generic issue in the Export functionality of the SAP ALV Grid component. Please report an incident on SAP component **BC-SRV-ALV**., describing your issue in detail. You can omit the Google Sheets integration as this will occur also in the local file export.

At this point in time I'm closing this issue. It must be further pursued via the official SAP support channel. 

Kind Regards,
Sebastian

**Closed as completed by SAPSM** 2022-09-27 08:06 UTC
